-------------------------------------------------------
----文件名		：	aliasdefine.lua
----创建者		：	xuantao@kingsoft.com
----创建时间	：	2011/8/19 19:16:08
----功能描述	：	一些快捷键的定义
--------------------------------------------------------
-- 快捷键可以生效的状态，多选相加
UiShortcutAlias.emKSTATE_INGAME = 1 -- 游戏世界内，默认
UiShortcutAlias.emKSTATE_LOCK = 2 -- 黑屏模式，Say对话框弹出
UiShortcutAlias.emKSTATE_MENU = 4 -- 登陆、选角色界面

-- 快捷键的执行细节
UiShortcutAlias.emDETAIL_EXCUTE_STRING = 1 -- 直接执行一段支付串
UiShortcutAlias.emDETAIL_EXCUTE_CALLBACK = 2 -- 是一个table，可以支持Lib:CallBack(tbCallBack)的格式
UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP = 3 -- 是一个窗口接收

-- 一些键的解释
UiShortcutAlias.tbExplanAlias = {
  ["LButton"] = "鼠标左键",
  ["RButton"] = "鼠标右键",
  ["Enter"] = "回车",
  ["`"] = "~",
}

UiShortcutAlias.tbShortExplanAlias = {
  ["Ctrl"] = "C",
  ["Alt"] = "A",
  ["Shift"] = "S",
}

-- 默认的快捷键的定义
UiShortcutAlias.tbDefault = {
  ["ClearMessage"] = {
    tbKey = { "Del", "Del" }, -- 对应键值，两种模式下的快捷键
    szDesc = "清除当前聊天信息输出栏内的信息", -- 描述
    tbExcute = { "Ui(Ui.UI_MSGPAD):ClearActiveTabMsg()" }, -- 执行参数，如果是窗口接收的话，这里的数据就是参数
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING, -- 执行方式
    nState = UiShortcutAlias.emKSTATE_INGAME, -- 可用状态
    szBelong = "", -- 所属窗口,表示哪个窗口接收事件
  },
  ["Quit"] = {
    tbKey = { "Alt+Q", "Alt+Q" },
    szDesc = "强行退出游戏",
    tbExcute = { "Exit()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["Exit"] = {
    tbKey = { "Alt+X", "Alt+X" },
    szDesc = "强行退出游戏",
    tbExcute = { "ExitGame()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["Input"] = {
    tbKey = { "Enter", "Enter" },
    szDesc = "激活输入文字框以及确认输入的文字，在某些对话框里为确认",
    tbExcute = { "Focus([[commandline]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["EmoteMenu"] = {
    tbKey = { "Alt+RButton", "Alt+RButton" },
    szDesc = "",
    tbExcute = { "Mouse_Emote_Menu()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["Force0"] = {
    tbKey = { "Shift+LButton", "Shift+LButton" },
    szDesc = "",
    tbExcute = { "Mouse_Force0()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["Force1"] = {
    tbKey = { "Shift+RButton", "Shift+RButton" },
    szDesc = "",
    tbExcute = { "Mouse_Force1()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["Menu"] = {
    tbKey = { "Ctrl+RButton", "Ctrl+RButton" },
    szDesc = "",
    tbExcute = { "Mouse_Menu()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["Talk"] = {
    tbKey = { "Ctrl+LButton", "Ctrl+LButton" },
    szDesc = "",
    tbExcute = { "Mouse_Say()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["LockCurSelect"] = {
    tbKey = { "L", "L" },
    szDesc = "锁定当前指向对象",
    tbExcute = { "UiManager:LockCurSelect()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ChangeAutoSelect"] = {
    tbKey = { "Ctrl+L", "Ctrl+L" },
    szDesc = "切换自动锁定当前指向对象",
    tbExcute = { "UiManager:ChangeAutoSelect()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchFullWindoMode"] = {
    tbKey = { "Alt+Enter", "Alt+Enter" },
    szDesc = "切换全屏 / 窗口模式",
    tbExcute = { "SetFullScreen()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK + UiShortcutAlias.emKSTATE_MENU,
    szBelong = "",
  },
  ["HelpPanel"] = {
    tbKey = { "", "" },
    szDesc = "",
    tbExcute = { "Open([[help]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  --	["HelpPanel"]		= {
  --		tbKey		= {"", ""},
  --		szDesc		= "",
  --		tbExcute	= {"Open([[help]])"},
  --		nExcute		= UiShortcutAlias.emDETAIL_EXCUTE_STRING,
  --		nState		= UiShortcutAlias.emKSTATE_INGAME,
  --		szBelong	= "",
  --	},
  ["MISSILESAME"] = {
    tbKey = { "Alt+S", "Alt+S" },
    szDesc = "",
    tbExcute = { "Open([[MissileSame]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["PLAYERNPC"] = {
    tbKey = { "Alt+D", "Alt+D" },
    szDesc = "",
    tbExcute = { "Open([[PlayerNpc]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SystemPanel"] = {
    tbKey = { "Esc", "Esc" },
    szDesc = "在主界面下弹出系统设置界面，在其它界面中则是关闭当前浮动窗口",
    tbExcute = { "UiManager:OnPressESC()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["VISIBLEPLAYER"] = {
    tbKey = { "Alt+F", "Alt+F" },
    szDesc = "",
    tbExcute = { "Open([[VisiblePlayer]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["PrintScreen"] = {
    tbKey = { "PrintScreen", "PrintScreen" },
    szDesc = "截图",
    tbExcute = { "UiManager:PrintScreen(1)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["ShortcutItem1"] = {
    tbKey = { "1", "1" },
    szDesc = "使用 1~10 快捷栏上的物品或者技能",
    tbExcute = { 0 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(0)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem2"] = {
    tbKey = { "2", "2" },
    szDesc = "",
    tbExcute = { 1 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(1)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem3"] = {
    tbKey = { "3", "3" },
    szDesc = "",
    tbExcute = { 2 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(2)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem4"] = {
    tbKey = { "4", "4" },
    szDesc = "",
    tbExcute = { 3 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(3)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem5"] = {
    tbKey = { "5", "5" },
    szDesc = "",
    tbExcute = { 4 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(4)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem6"] = {
    tbKey = { "6", "6" },
    szDesc = "",
    tbExcute = { 5 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(5)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem7"] = {
    tbKey = { "7", "7" },
    szDesc = "",
    tbExcute = { 6 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(6)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem8"] = {
    tbKey = { "8", "8" },
    szDesc = "",
    tbExcute = { 7 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(7)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem9"] = {
    tbKey = { "9", "9" },
    szDesc = "",
    tbExcute = { 8 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(8)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutItem10"] = {
    tbKey = { "0", "0" },
    szDesc = "",
    tbExcute = { 9 }, --{"Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(9)"},
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_UIGROUP,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = Ui.UI_SHORTCUTBAR,
  },
  ["ShortcutSkill0"] = {
    tbKey = { "Q", "F1" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill1"] = {
    tbKey = { "W", "F2" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(1)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill2"] = {
    tbKey = { "E", "F3" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(2)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill3"] = {
    tbKey = { "A", "F4" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(3)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill4"] = {
    tbKey = { "S", "F5" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(4)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill5"] = {
    tbKey = { "D", "F6" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(5)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill6"] = {
    tbKey = { "Z", "F7" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(6)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill7"] = {
    tbKey = { "X", "F8" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(7)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill8"] = {
    tbKey = { "C", "F9" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(8)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill9"] = {
    tbKey = { "Z", "F10" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(10)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill10"] = {
    tbKey = { "X", "F11" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(11)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShortcutSkill11"] = {
    tbKey = { "C", "F12" },
    szDesc = "",
    tbExcute = { "UiShortcutAlias:ShortcutSkill(12)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchMount"] = {
    tbKey = { "M", "M" },
    szDesc = "切换上 / 下马",
    tbExcute = { "Switch([[horse]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchPK"] = {
    tbKey = { "Ctrl+H", "Ctrl+H" },
    szDesc = "切换 PK 模式",
    tbExcute = { "Ui(Ui.UI_POPBAR):ChangeToNextModel()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchRun"] = {
    tbKey = { "R", "R" },
    szDesc = "切换走路 / 跑步模式",
    tbExcute = { "Switch([[run]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchCarrier"] = {
    tbKey = { "N", "N" },
    szDesc = "切换上 / 下载具",
    tbExcute = { "UiManager:OnNKeyDown()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchSit"] = {
    tbKey = { "V", "V" },
    szDesc = "切换打坐 / 站立状态",
    tbExcute = { "Switch([[sit]])" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["OpenFightPower"] = {
    tbKey = { "Y", "Y" },
    szDesc = "打开战斗力界面",
    tbExcute = { "Ui(Ui.UI_PLAYERSTATE):CmdViewFightPower()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["WorldMap"] = {
    tbKey = { "Tab", "Tab" },
    szDesc = "打开世界地图",
    tbExcute = {
      [[
				if UiManager:WindowVisible(Ui.UI_WORLDMAP_AREA) == 1 then
					UiManager:CloseWindow(Ui.UI_WORLDMAP_AREA);
				elseif UiManager:WindowVisible(Ui.UI_WORLDMAP_GLOBAL) == 1 then
					UiManager:CloseWindow(Ui.UI_WORLDMAP_GLOBAL);
				elseif UiManager:WindowVisible(Ui.UI_WORLDMAP_DOMAIN) == 1 then
					UiManager:CloseWindow(Ui.UI_WORLDMAP_DOMAIN);
				else
					local nCurMapId, nWorldPosX, nWorldPosY = me.GetWorldPos();
					if (not MODULE_GAMESERVER) then
						nCurMapId = me.nTemplateMapId;
					end
					UiManager:SwitchWindow(Ui.UI_WORLDMAP_SUB, nCurMapId);
				end
			]],
    },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchChannel"] = {
    tbKey = { "Insert", "Insert" },
    szDesc = "切换聊天频道",
    tbExcute = { "Ui(Ui.UI_CHATTAB):SwitchPrivateMsgMode()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchShowLife"] = {
    tbKey = { "[", "[" },
    szDesc = "显示角色名字",
    tbExcute = { "Ui(Ui.UI_SYSTEM):SwitchShowLife()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchShowName"] = {
    tbKey = { "]", "]" },
    szDesc = "显示角色血条",
    tbExcute = { "Ui(Ui.UI_SYSTEM):SwitchShowName()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchShowItem"] = {
    tbKey = { "Alt+Space", "Alt+Space" },
    szDesc = "切换显示 / 隐藏地上 Obj 的名字",
    tbExcute = { "Ui(Ui.UI_SYSTEM):SwtichShowItem()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVEDOWN_N"] = {
    tbKey = { "NUM2", "NUM2" },
    szDesc = "向下走",
    tbExcute = { "MoveTo(0,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVELEFTDOWN_N"] = {
    tbKey = { "NUM1", "NUM1" },
    szDesc = "向左下走",
    tbExcute = { "MoveTo(8,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVELEFT_N"] = {
    tbKey = { "NUM4", "NUM4" },
    szDesc = "向左走",
    tbExcute = { "MoveTo(16,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVELEFTUP_N"] = {
    tbKey = { "NUM7", "NUM7" },
    szDesc = "向左上走",
    tbExcute = { "MoveTo(24,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVEUP_N"] = {
    tbKey = { "NUM8", "NUM8" },
    szDesc = "向上走",
    tbExcute = { "MoveTo(32,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVERIGHTUP_N"] = {
    tbKey = { "NUM9", "NUM9" },
    szDesc = "向右上走",
    tbExcute = { "MoveTo(40,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVERIGHT_N"] = {
    tbKey = { "NUM6", "NUM6" },
    szDesc = "向右走",
    tbExcute = { "MoveTo(48,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MOVERIGHTDOWN_N"] = {
    tbKey = { "NUM3", "NUM3" },
    szDesc = "向右下走",
    tbExcute = { "MoveTo(56,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveDown"] = {
    tbKey = { "Down", "Down" },
    szDesc = "向下走",
    tbExcute = { "MoveTo(0,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveLeftDown"] = {
    tbKey = { "Down+Left", "Down+Left" },
    szDesc = "向左下走",
    tbExcute = { "MoveTo(8,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveLeft"] = {
    tbKey = { "Left", "Left" },
    szDesc = "向左走",
    tbExcute = { "MoveTo(16,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveLeftUp"] = {
    tbKey = { "Left+Up", "Left+Up" },
    szDesc = "向左上走",
    tbExcute = { "MoveTo(24,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveUp"] = {
    tbKey = { "Up", "Up" },
    szDesc = "向上走",
    tbExcute = { "MoveTo(32,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveUpRight"] = {
    tbKey = { "Up+Right", "Up+Right" },
    szDesc = "向右上走",
    tbExcute = { "MoveTo(40,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveRight"] = {
    tbKey = { "Right", "Right" },
    szDesc = "向右走",
    tbExcute = { "MoveTo(48,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["MoveRightDown"] = {
    tbKey = { "Right+Down", "Right+Down" },
    szDesc = "向右下走",
    tbExcute = { "MoveTo(56,	0)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchUiModel"] = {
    tbKey = { "Ctrl+Tab", "Ctrl+Tab" },
    szDesc = "切换界面模式",
    tbExcute = { "UiManager:SwitchUiModel()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["BattleReport"] = {
    tbKey = { "`", "`" },
    szDesc = "打开即时活动战报",
    tbExcute = { "UiShortcutAlias:OpenCampaignUi()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["PlayerPanel"] = {
    tbKey = { "F1", "Q" },
    szDesc = "打开主角属性面版",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_PLAYERPANEL)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ItemBoxPalen"] = {
    tbKey = { "F2", "W" },
    szDesc = "打开物品栏",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_ITEMBOX)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SkillPanel"] = {
    tbKey = { "F3", "E" },
    szDesc = "打开技能界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_FIGHTSKILL)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["TaskPanel"] = {
    tbKey = { "F4", "A" },
    szDesc = "打开任务记录界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_TASKPANEL)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["RelationPanel"] = {
    tbKey = { "F5", "S" },
    szDesc = "打开人际关系列表",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_RELATIONNEW)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["TongPanel"] = {
    tbKey = { "F7", "F" },
    szDesc = "打开帮会界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_TONG)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["LifeSkillPanel"] = {
    tbKey = { "F8", "B" },
    szDesc = "打开生活技能界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_LIFESKILL);print(123);" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["partner"] = {
    tbKey = { "F9", "F9" },
    szDesc = "打开同伴界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_PARTNER)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["zhenyuan"] = {
    tbKey = { "F10", "F10" },
    szDesc = "打开真元界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_ZHENYUAN)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["DirectClose"] = {
    tbKey = { "F11", "X" },
    szDesc = "打开系统设置界面",
    tbExcute = { "UiManager:OnReadyEsc()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["HelpSprite"] = {
    tbKey = { "F12", "Z" },
    szDesc = "打开帮助锦囊",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_HELPSPRITE)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["TextExEditor"] = {
    tbKey = { "Ctrl+Alt+F12", "Ctrl+Alt+Z" },
    szDesc = "打开文本编辑器",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_TEXTEXEDITOR)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK + UiShortcutAlias.emKSTATE_MENU,
    szBelong = "",
  },
  ["MailPanel"] = {
    tbKey = { "I", "I" },
    szDesc = "打开邮箱界面",
    tbExcute = { "Mail:SwitchWindow()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["TeamPanel"] = {
    tbKey = { "P", "P" },
    szDesc = "打开队伍界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_TEAM)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["TeacherPanel"] = {
    tbKey = { "H", "H" },
    szDesc = "打开 师徒 界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_TEACHER)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["LEFTBUTTON"] = {
    tbKey = { "LButton", "LButton" },
    szDesc = "",
    tbExcute = { "UiManager:OnLButtonDown()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["RIGHTBUTTON"] = {
    tbKey = { "RButton", "RButton" },
    szDesc = "",
    tbExcute = { "UiManager:OnRButtonDown()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SWITCHEQUIP"] = {
    tbKey = { "Ctrl+W", "Ctrl+W" },
    szDesc = "切换装备",
    tbExcute = { "Ui(Ui.UI_PLAYERPANEL):ApplySwitchEquip(1)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SWITCHDEBUG"] = {
    tbKey = { "Ctrl+D", "Ctrl+D" },
    szDesc = "切换调试信息显示",
    tbExcute = { "if SwitchDebugInfo then SwitchDebugInfo(1) end" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SWITCHDEBUG_BACK"] = {
    tbKey = { "Ctrl+Shift+D", "Ctrl+Shift+D" },
    szDesc = "回滚切换调试信息显示",
    tbExcute = { "if SwitchDebugInfo then SwitchDebugInfo(-1) end" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["ShowTempMode(1)"] = {
    tbKey = { "Ctrl+I", "Ctrl+I" },
    szDesc = "临时切换至战场即时消息",
    tbExcute = { "Ui(Ui.UI_TASKTRACK):ShowTempMode(1)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["SwitchSplitItemState()"] = {
    tbKey = { "Ctrl+S", "Ctrl+S" },
    szDesc = "拆分道具状态",
    tbExcute = { "Ui(Ui.UI_ITEMBOX):SwitchSplitItemState()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["UI_IBSHOP"] = {
    tbKey = { "Ctrl+G", "Ctrl+G" },
    szDesc = "打开奇珍阁",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_IBSHOP)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["Space"] = {
    tbKey = { "Space", "Space" },
    szDesc = "拾取物品",
    tbExcute = { "AutoAi.PickAroundItem()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["UI_LADDER"] = {
    tbKey = { "Ctrl+C", "Ctrl+C" },
    szDesc = "打开排行榜",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_LADDER)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["AutoFight"] = {
    tbKey = { "Ctrl+F", "Ctrl+F" },
    szDesc = "自动战斗",
    tbExcute = { "AutoAi:UpdateCfg(Ui.tbLogic.tbAutoFightData:ShortKey())" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["AutoFight2"] = {
    tbKey = { "F", "Ctrl+F" },
    szDesc = "自动战斗",
    tbExcute = { "AutoAi:UpdateCfg(Ui.tbLogic.tbAutoFightData:ShortKey())" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["AutoMed"] = {
    tbKey = { "Ctrl+Z", "Ctrl+Z" },
    szDesc = "自动吃药",
    tbExcute = { "Ui(Ui.UI_AUTOFIGHT):StartAutoMed()" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["activegift"] = {
    tbKey = { "J", "J" },
    szDesc = "活跃度",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_ACTIVEGIFT)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["Calendar"] = {
    tbKey = { "K", "K" },
    szDesc = "打开剑侠日历",
    tbExcute = {
      [[
				if UiManager.IVER_bOpenCalendar == 1 then
					UiManager:SwitchWindow(Ui.UI_NEWCALENDARVIEW)
				end
			]],
    },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["UI_DAILY"] = {
    tbKey = { "Ctrl+B", "Ctrl+B" },
    szDesc = "剑侠日报",
    tbExcute = {
      [[
				if IsDailyOpen() == 1 then
					if UiManager.IVER_nOpenDaily == 1 then
						UiManager:SwitchWindow(Ui.UI_DAILY)
					end
				end
			]],
    },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["UI_AUCTIONROOM"] = {
    tbKey = { "T", "T" },
    szDesc = "拍卖行",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_AUCTIONROOM, 1)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["UI_ACHIEVEMENT"] = {
    tbKey = { "U", "U" },
    szDesc = "打开成就界面",
    tbExcute = { "UiManager:SwitchWindow(Ui.UI_ACHIEVEMENT)" },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },
  ["KinPanel"] = {
    tbKey = { "F6", "D" },
    szDesc = "打开家族界面",
    tbExcute = {
      [[
				if KKin.GetSelfKin() then
					UiManager:SwitchWindow(Ui.UI_KIN);
				else
					UiManager:SwitchWindow(Ui.UI_KINRCM_LIST);
				end
			]],
    },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME,
    szBelong = "",
  },

  --------------------------------------------------------------------------------------------------------------------------
  -- GM指令
  ["GM_S1"] = {
    tbKey = { "Ctrl+1", "Ctrl+1" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds TI(1)")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S2"] = {
    tbKey = { "Ctrl+2", "Ctrl+2" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds TI(2)")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S3"] = {
    tbKey = { "Ctrl+3", "Ctrl+3" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds TI(3)")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S4"] = {
    tbKey = { "Ctrl+4", "Ctrl+4" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds RESTORE()")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S5"] = {
    tbKey = { "Ctrl+5", "Ctrl+5" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds me.SetFightState(1-me.nFightState)")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S6"] = {
    tbKey = { "Ctrl+6", "Ctrl+6" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds Lib._SuperScript:DoScriptDir()")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S7"] = {
    tbKey = { "Ctrl+7", "Ctrl+7" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds GM.tbPlayer:GMShortcutailasCmd()")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S8"] = {
    tbKey = { "Ctrl+8", "Ctrl+8" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds FightSkill:DamageAccount(me.nId)")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S9"] = {
    tbKey = { "Ctrl+9", "Ctrl+9" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?gm ds sj()")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_S10"] = {
    tbKey = { "Ctrl+0", "Ctrl+0" },
    szDesc = "",
    tbExcute = { 'SendChannelMsg("GM", "?pl CallNpc(3596,255,0,0)")' },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C1"] = {
    tbKey = { "Alt+1", "Alt+1" },
    szDesc = "",
    tbExcute = { [[Ui:OpenDebugMode()]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C2"] = {
    tbKey = { "Alt+2", "Alt+2" },
    szDesc = "",
    tbExcute = { [[FightSkill:ReloadFile()]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C3"] = {
    tbKey = { "Alt+3", "Alt+3" },
    szDesc = "",
    tbExcute = { [[FightSkill:ClearCDTime()]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C4"] = {
    tbKey = { "Alt+4", "Alt+4" },
    szDesc = "",
    tbExcute = { [[me.Msg("GM指令未设定")]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C5"] = {
    tbKey = { "Alt+5", "Alt+5" },
    szDesc = "",
    tbExcute = { [[me.Msg("GM指令未设定")]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C6"] = {
    tbKey = { "Alt+6", "Alt+6" },
    szDesc = "",
    tbExcute = { [[me.Msg("GM指令未设定")]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C7"] = {
    tbKey = { "Alt+7", "Alt+7" },
    szDesc = "",
    tbExcute = { [[me.Msg("GM指令未设定")]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C8"] = {
    tbKey = { "Alt+8", "Alt+8" },
    szDesc = "",
    tbExcute = { [[me.Msg("GM指令未设定")]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C9"] = {
    tbKey = { "Alt+9", "Alt+9" },
    szDesc = "",
    tbExcute = { [[me.Msg("GM指令未设定")]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
    szBelong = "",
  },
  ["GM_C10"] = {
    tbKey = { "Alt+0", "Alt+0" },
    szDesc = "",
    tbExcute = { [[Console()]] },
    nExcute = UiShortcutAlias.emDETAIL_EXCUTE_STRING,
    nState = UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK + UiShortcutAlias.emKSTATE_MENU,
    szBelong = "",
  },
}

-----------------------------------------------------------------------------------------------------------------------------
-- 向后兼容的内容，一下的东西不再更新
-- 也顺便继续支持插件
UiShortcutAlias.m_tKeyList = {
  --[1]:执行命令,[2]:键值,[3]:名字描述？,[4]模式1快捷键,[5]模式2快捷键,[6]快捷键描述,[7]状态
  { "Ui(Ui.UI_MSGPAD):ClearActiveTabMsg()", "ClearMessage", "cls", "Del", "Del", "清除当前聊天信息输出栏内的信息" },
  { "Exit()", "Quit", "quit", "Alt+Q", "Alt+Q", "强行退出游戏", UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK },
  { "ExitGame()", "Exit", "exit", "Alt+X", "Alt+X", "强行退出游戏", UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK },
  {
    "Focus([[commandline]])",
    "Input",
    "",
    "Enter",
    "Enter",
    "激活输入文字框以及确认输入的文字，在某些对话框里为确认",
    UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
  },
  { "Mouse_Emote_Menu()", "EmoteMenu", "", "Alt+RButton", "Alt+RButton", "" },
  { "Mouse_Force0()", "Force0", "", "Shift+LButton", "Shift+LButton", "" },
  { "Mouse_Force1()", "Force1", "", "Shift+RButton", "Shift+RButton", "" },
  { "Mouse_Menu()", "Menu", "", "Ctrl+RButton", "Ctrl+RButton", "" },
  { "Mouse_Say()", "Talk", "", "Ctrl+LButton", "Ctrl+LButton", "" },
  { "UiManager:LockCurSelect()", "LockCurSelect", "", "L", "L", "锁定当前指向对象" },
  { "UiManager:ChangeAutoSelect()", "ChangeAutoSelect", "", "Ctrl+L", "Ctrl+L", "切换自动锁定当前指向对象" },
  {
    "SetFullScreen()",
    "SwitchFullWindoMode",
    "",
    "Alt+Enter",
    "Alt+Enter",
    "切换全屏 / 窗口模式",
    UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK + UiShortcutAlias.emKSTATE_MENU,
  },
  { "Open([[help]])", "HelpPanel", "帮助", "", "", "" },
  { "Open([[help]])", "HelpPanel", "bz", "", "", "" },
  --{ "Open([[map]], 2)", "SwitchMiniMap", "", "Tab", "Tab", "切换小地图状态" },
  { "Open([[MissileSame]])", "", "", "Alt+S", "Alt+S", "" },
  { "Open([[PlayerNpc]])", "", "", "Alt+D", "Alt+D", "" },
  { "UiManager:OnPressESC()", "SystemPanel", "", "Esc", "Esc", "在主界面下弹出系统设置界面，在其它界面中则是关闭当前浮动窗口" },
  { "Open([[VisiblePlayer]])", "", "", "Alt+F", "Alt+F", "" },
  { "UiManager:PrintScreen(1)", "PrintScreen", "", "PrintScreen", "PrintScreen", "截图", UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(0)", "ShortcutItem1", "", "1", "1", "使用 1~10 快捷栏上的物品或者技能" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(1)", "ShortcutItem2", "", "2", "2" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(2)", "ShortcutItem3", "", "3", "3" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(3)", "ShortcutItem4", "", "4", "4" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(4)", "ShortcutItem5", "", "5", "5" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(5)", "ShortcutItem6", "", "6", "6" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(6)", "ShortcutItem7", "", "7", "7" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(7)", "ShortcutItem8", "", "8", "8" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(8)", "ShortcutItem9", "", "9", "9" },
  { "Ui(Ui.UI_SHORTCUTBAR):OnUseShortcutObj(9)", "ShortcutItem10", "", "0", "0" },
  { "UiShortcutAlias:ShortcutSkill(0)", "ShortcutSkill0", "", "Q", "F1" },
  { "UiShortcutAlias:ShortcutSkill(1)", "ShortcutSkill1", "", "W", "F2" },
  { "UiShortcutAlias:ShortcutSkill(2)", "ShortcutSkill2", "", "E", "F3" },
  { "UiShortcutAlias:ShortcutSkill(3)", "ShortcutSkill3", "", "A", "F4" },
  { "UiShortcutAlias:ShortcutSkill(4)", "ShortcutSkill4", "", "S", "F5" },
  { "UiShortcutAlias:ShortcutSkill(5)", "ShortcutSkill5", "", "D", "F6" },
  { "UiShortcutAlias:ShortcutSkill(6)", "ShortcutSkill6", "", "Z", "F7" },
  { "UiShortcutAlias:ShortcutSkill(7)", "ShortcutSkill7", "", "X", "F8", "" },
  { "UiShortcutAlias:ShortcutSkill(8)", "ShortcutSkill8", "", "C", "F9", "" },
  { "UiShortcutAlias:ShortcutSkill(10)", "ShortcutSkill9", "", "Z", "F10", "" },
  { "UiShortcutAlias:ShortcutSkill(11)", "ShortcutSkill10", "", "X", "F11", "" },
  { "UiShortcutAlias:ShortcutSkill(12)", "ShortcutSkill11", "", "C", "F12", "" },
  { "Switch([[horse]])", "SwitchMount", "", "M", "M", "切换上 / 下马" },
  { "Ui(Ui.UI_POPBAR):ChangeToNextModel()", "SwitchPK", "", "Ctrl+H", "Ctrl+H", "切换 PK 模式" },
  { "Switch([[run]])", "SwitchRun", "", "R", "R", "切换走路 / 跑步模式" },
  { "Switch([[sit]])", "SwitchSit", "", "V", "V", "切换打坐 / 站立状态" },
  { "Ui(Ui.UI_PLAYERSTATE):CmdViewFightPower()", "OpenFightPower", "", "Y", "Y", "打开战斗力界面" },
  { "Switch([[carrier]])", "SwitchCarrier", "", "N", "N", "切换上 / 下载具" },
  {
    [[
				if UiManager:WindowVisible(Ui.UI_WORLDMAP_AREA) == 1 then
					UiManager:CloseWindow(Ui.UI_WORLDMAP_AREA);
				elseif UiManager:WindowVisible(Ui.UI_WORLDMAP_GLOBAL) == 1 then
					UiManager:CloseWindow(Ui.UI_WORLDMAP_GLOBAL);
				elseif UiManager:WindowVisible(Ui.UI_WORLDMAP_DOMAIN) == 1 then
					UiManager:CloseWindow(Ui.UI_WORLDMAP_DOMAIN);
				else
					local nCurMapId, nWorldPosX, nWorldPosY = me.GetWorldPos();	
					if (not MODULE_GAMESERVER) then
						nCurMapId = me.nTemplateMapId;
					end
					UiManager:SwitchWindow(Ui.UI_WORLDMAP_SUB, nCurMapId);
				end
			]],
    "WorldMap",
    "",
    "Tab",
    "Tab",
    "打开世界地图",
  },
  { "Ui(Ui.UI_CHATTAB):SwitchPrivateMsgMode()", "SwitchChannel", "", "Insert", "Insert", "切换聊天频道" },
  { "Ui(Ui.UI_SYSTEM):SwitchShowLife()", "SwitchShowLife", "", "[", "[", "显示角色名字" },
  { "Ui(Ui.UI_SYSTEM):SwitchShowName()", "SwitchShowName", "", "]", "]", "显示角色血条" },
  { "Ui(Ui.UI_SYSTEM):SwtichShowItem()", "SwitchShowItem", "", "Alt+Space", "Alt+Space", "切换显示 / 隐藏地上 Obj 的名字" },

  { "MoveTo(0,	0)", "MoveDown", "", "NUM2", "NUM2", "向下走" },
  { "MoveTo(8,	0)", "MoveLeftDown", "", "NUM1", "NUM1", "向左下走" },
  { "MoveTo(16,	0)", "MoveLeft", "", "NUM4", "NUM4", "向左走" },
  { "MoveTo(24,	0)", "MoveLeftUp", "", "NUM7", "NUM7", "向左上走" },
  { "MoveTo(32,	0)", "MoveUp", "", "NUM8", "NUM8", "向上走" },
  { "MoveTo(40,	0)", "MoveUpRight", "", "NUM9", "NUM9", "向右上走" },
  { "MoveTo(48,	0)", "MoveRight", "", "NUM6", "NUM6", "向右走" },
  { "MoveTo(56,	0)", "MoveRightDown", "", "NUM3", "NUM3", "向右下走" },

  { "MoveTo(0,	0)", "MoveDown", "", "Down", "Down", "向下走" },
  { "MoveTo(8,	0)", "MoveLeftDown", "", "Down+Left", "Down+Left", "向左下走" },
  { "MoveTo(16,	0)", "MoveLeft", "", "Left", "Left", "向左走" },
  { "MoveTo(24,	0)", "MoveLeftUp", "", "Left+Up", "Left+Up", "向左上走" },
  { "MoveTo(32,	0)", "MoveUp", "", "Up", "Up", "向上走" },
  { "MoveTo(40,	0)", "MoveUpRight", "", "Up+Right", "Up+Right", "向右上走" },
  { "MoveTo(48,	0)", "MoveRight", "", "Right", "Right", "向右走" },
  { "MoveTo(56,	0)", "MoveRightDown", "", "Right+Down", "Right+Down", "向右下走" },

  { "UiManager:SwitchUiModel()", "SwitchUiModel", "", "Ctrl+Tab", "Ctrl+Tab", "切换界面模式" },

  { "UiShortcutAlias:OpenCampaignUi()", "BattleReport", "", "`", "`", "打开即时活动战报" }, -- UNDONE: zbl	新添的,不知道对不对,先放着
  -- F1~F12
  { "UiManager:SwitchWindow(Ui.UI_PLAYERPANEL)", "PlayerPanel", "", "F1", "Q", "打开主角属性面版" },
  { "UiManager:SwitchWindow(Ui.UI_ITEMBOX)", "ItemBoxPalen", "", "F2", "W", "打开物品栏" },
  { "UiManager:SwitchWindow(Ui.UI_FIGHTSKILL)", "SkillPanel", "", "F3", "E", "打开技能界面" },
  { "UiManager:SwitchWindow(Ui.UI_TASKPANEL)", "TaskPanel", "", "F4", "A", "打开任务记录界面" },
  { "UiManager:SwitchWindow(Ui.UI_RELATIONNEW)", "RelationPanel", "", "F5", "S", "打开人际关系列表" },
  --		{ "UiManager:SwitchWindow(Ui.UI_KIN)",			"KinPanel",		"",	"F6",	"D",	"打开家族界面" },
  { "UiManager:SwitchWindow(Ui.UI_TONG)", "TongPanel", "", "F7", "F", "打开帮会界面" },
  { "UiManager:SwitchWindow(Ui.UI_LIFESKILL)", "LifeSkillPanel", "", "F8", "B", "打开生活技能界面" },
  -- F9 预留
  { "UiManager:SwitchWindow(Ui.UI_PARTNER)", "partner", "", "F9", "F9", "打开同伴界面" },
  -- F10 预留
  { "UiManager:SwitchWindow(Ui.UI_ZHENYUAN)", "zhenyuan", "", "F10", "F10", "打开真元界面" },
  { "UiManager:OnReadyEsc()", "DirectClose", "", "F11", "X", "打开系统设置界面" },
  {
    "UiManager:SwitchWindow(Ui.UI_HELPSPRITE)",
    "HelpSprite",
    "",
    "F12",
    "Z",
    "打开帮助锦囊",
    UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
  },
  {
    "UiManager:SwitchWindow(Ui.UI_TEXTEXEDITOR)",
    "TextExEditor",
    "",
    "Ctrl+Alt+F12",
    "Ctrl+Alt+Z",
    "打开文本编辑器",
    UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK + UiShortcutAlias.emKSTATE_MENU,
  },
  { "Mail:SwitchWindow()", "MailPanel", "", "I", "I", "打开邮箱界面" },
  { "UiManager:SwitchWindow(Ui.UI_TEAM)", "TeamPanel", "team", "P", "P", "打开队伍界面" },
  { "UiManager:SwitchWindow(Ui.UI_TEACHER)", "TeacherPanel", "", "H", "H", "打开 师徒 界面" },
  { "UiManager:OnLButtonDown()", "LButton", "", "LButton", "LButton", "" },
  { "UiManager:OnRButtonDown()", "RButton", "", "RButton", "RButton", "" },
  { "Ui(Ui.UI_PLAYERPANEL):ApplySwitchEquip(1)", "SwitchEquip", "", "Ctrl+W", "Ctrl+W", "切换装备" },
  { "if SwitchDebugInfo then SwitchDebugInfo(1) end", "SwitchDebugInfo(1)", "", "Ctrl+D", "Ctrl+D", "切换调试信息显示" },
  { "if SwitchDebugInfo then SwitchDebugInfo(-1) end", "SwitchDebugInfo(-1)", "", "Ctrl+Shift+D", "Ctrl+Shift+D", "回滚切换调试信息显示" },
  { "Ui(Ui.UI_TASKTRACK):ShowTempMode(1)", "ShowTempMode(1)", "", "Ctrl+I", "Ctrl+I", "临时切换至战场即时消息" },
  { "Ui(Ui.UI_ITEMBOX):SwitchSplitItemState()", "SwitchSplitItemState()", "", "Ctrl+S", "Ctrl+S", "拆分道具状态" },
  { "UiManager:SwitchWindow(Ui.UI_IBSHOP)", "UI_IBSHOP", "", "Ctrl+G", "Ctrl+G", "打开奇珍阁" },
  { "AutoAi.PickAroundItem()", "PickItem", "", "Space", "Space", "拾取物品" },
  { "UiManager:SwitchWindow(Ui.UI_LADDER)", "UI_LADDER", "", "Ctrl+C", "Ctrl+C", "打开排行榜" },
  { "AutoAi:UpdateCfg(Ui.tbLogic.tbAutoFightData:ShortKey())", "AutoFight", "", "Ctrl+F", "Ctrl+F", "自动战斗" },
  { "AutoAi:UpdateCfg(Ui.tbLogic.tbAutoFightData:ShortKey())", "AutoFight", "", "F", "Ctrl+F", "自动战斗" },
  { "Ui(Ui.UI_AUTOFIGHT):StartAutoMed()", "AutoMed", "", "Ctrl+Z", "Ctrl+Z", "自动吃药" },
  { "UiManager:SwitchWindow(Ui.UI_ACTIVEGIFT)", "activegift", "", "J", "J", "活跃度" },
  {
    [[
			if UiManager.IVER_bOpenCalendar == 1 then
				UiManager:SwitchWindow(Ui.UI_NEWCALENDARVIEW)
			end
			]],
    "FunbenInfo",
    "",
    "K",
    "K",
    "打开剑侠日历",
    UiShortcutAlias.emKSTATE_INGAME + UiShortcutAlias.emKSTATE_LOCK,
  },
  {
    [[
			if IsDailyOpen() == 1 then
				if UiManager.IVER_nOpenDaily == 1 then
					UiManager:SwitchWindow(Ui.UI_DAILY)
				end
			end
			]],
    "UI_DAILY",
    "",
    "Ctrl+B",
    "Ctrl+B",
    "剑侠日报",
  },

  { "UiManager:SwitchWindow(Ui.UI_AUCTIONROOM, 1)", "UI_AUCTIONROOM", "", "T", "T", "拍卖行" },
  { "UiManager:SwitchWindow(Ui.UI_ACHIEVEMENT)", "UI_ACHIEVEMENT", "", "U", "U", "打开成就界面" },
  {
    [[
			if KKin.GetSelfKin() then
				UiManager:SwitchWindow(Ui.UI_KIN);
			else
				UiManager:SwitchWindow(Ui.UI_KINRCM_LIST);
			end
		 	]],
    "KinPanel",
    "",
    "F6",
    "D",
    "打开家族界面",
  },
}
